### ISSUE TITLE
Update ARCtrl and some additional dependencies

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/arc-export#4]

**Comment by kMutagene** [comment]
@hlweil what do you think how robust such an update will be? this tool is used on every commit on every arc on the datahub.

**Comment by HLWeil** [comment]
As the current ARCtrl version is used in ARCitect, I would expect the read-in to be fairly robust.

But there might be Issues with very old ARCs
https://github.com/nfdi4plants/ARCCommander/issues/240

**Comment by HLWeil** [comment]
We could also allow both ISA and RO-Crate json via CLI args. 

For RO-Crate I would first implement https://github.com/nfdi4plants/ARCtrl/issues/344, and then use that function here.
